### ISSUE TITLE
How to verify that ConfigureAwait(false) inserted.

### ISSUE THREAD

**Issue by MNF** [Fody/ConfigureAwait#10]
I've installed Install-Package ConfigureAwait.Fody and added   [ConfigureAwait(false)] attribute to my class.
However I am not sure that Fody does anything.
I've opened built DLL in JetBrains dotPeek and it shows the same code as I wrote- no extra ConfigureAwait(false).

Config has
```
<Weavers>
  <ConfigureAwait/>
</Weavers>
```

Build output:
4>    Fody: Fody (version 1.29.4.0) Executing
4>    Fody:   Finished Fody 10ms.
4>  MyProject -> C:\GitRepos\MyProject\bin\MyProject.dll
4>    Fody:   Skipped Verifying assembly since it is disabled in configuration
4>    Fody:   Finished verification in 0ms.

Please suggest what I am doing wrong?

**Comment by michael-freidgeim-webjet** [comment]
I found that it is a bug [Class with private field is ignored for weaving ](https://github.com/distantcam/ConfigureAwait/issues/11) 
However logging didn't help me.  Using <Weavers  ShowDebug="true"> doesn't add much information. Specify Tools > Options > Projects and Solutions > Build and Run > MSBuild project build output verbostiy provide a lot of output, but not much applicable for reosons why the weaver ignored the class

**Comment by orellabac** [comment]
I think this is not a bug. I think is that we as users were not understanding how the await is generated.
I say this because I came to this page looking for an answer but then I ran the unit tests and saw that they worked. 
So this is what I concluded.

If you look at the example:

```C#

    public class Example
    {
        public async Task AsyncMethod1()
        {
            await Task.Delay(1);
        }

        [ConfigureAwait(false)]
        public async Task AsyncMethod2()
        {
            await Task.Delay(1);
        }

        public async Task AsyncMethod3()
        {
            await Task.Delay(1).ConfigureAwait(false);
        }
```

And if you look at the decompilation on tools like ILSpy for example for `AsyncMethod2`:

```C#
// AssemblyToProcess.Example
[DebuggerStepThrough, AsyncStateMachine(typeof(Example.<AsyncMethod2>d__1))]
public Task AsyncMethod2()
{
	Example.<AsyncMethod2>d__1 <AsyncMethod2>d__ = new Example.<AsyncMethod2>d__1();
	<AsyncMethod2>d__.<>4__this = this;
	<AsyncMethod2>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
	<AsyncMethod2>d__.<>1__state = -1;
	AsyncTaskMethodBuilder <>t__builder = <AsyncMethod2>d__.<>t__builder;
	<>t__builder.Start<Example.<AsyncMethod2>d__1>(ref <AsyncMethod2>d__);
	return <AsyncMethod2>d__.<>t__builder.Task;
}

```

You would say, mmm where is the ConfigureAwait call. But if you look closer at the IL and specially at the StateMachine the IL Says
```Assembly
IL_000e: nop
IL_000f: ldc.i4.1
IL_0010: call class [mscorlib]System.Threading.Tasks.Task [mscorlib]System.Threading.Tasks.Task::Delay(int32)
IL_0015: ldc.i4.0
IL_0016: callvirt instance valuetype [mscorlib]System.Runtime.CompilerServices.ConfiguredTaskAwaitable [mscorlib]System.Threading.Tasks.Task::ConfigureAwait(bool)
IL_001b: stloc.2
IL_001c: ldloca.s 2
==> IL_001e: call instance valuetype [mscorlib]System.Runtime.CompilerServices.ConfiguredTaskAwaitable/ConfiguredTaskAwaiter [mscorlib]System.Runtime.CompilerServices.ConfiguredTaskAwaitable::GetAwaiter() 
IL_0023: stloc.1
IL_0024: ldloca.s 1
IL_0026: call instance bool [mscorlib]System.Runtime.CompilerServices.ConfiguredTaskAwaitable/ConfiguredTaskAwaiter::get_IsCompleted()
IL_002b: brtrue.s IL_006d
```
