### ISSUE TITLE
Version 3.3.0 fail for some builds.

### ISSUE THREAD

**Issue by blankensteiner** [Fody/ConfigureAwait#106]
We have just added support for ValueTask, but there is an unforeseen issue.

It works for all .NET Core versions and .NET Standard 2.1 libraries. 
However, .NET Standard 2.0 projects and .NET Framework what use ValueTask via the Nuget package "System.Threading.Tasks.Extensions" will now fail. The problem is that ModuleWeaver.Execute will not find "System.Threading.Tasks.ValueTask", but the project is actually using ValueTask, so when we get to AddAwaitConfigToAsyncMethod, we will get a NullReferenceException.

We could just guard against that, but then we end up with .NET Standard 2.0 and .NET Framework projects using ValueTask will only get ConfigureAwait(...) on Tasks and not on ValueTasks.

I am very new to Fody, so I don't quite know how this should be handled. I have tried different solutions, but "System.Threading.Tasks.Extensions" is just not present when Execute is called, so maybe we are forced to use some static IL? I don't know if that is possible in this case or a good idea, or if there is some way to get it to find System.Threading.Tasks.Extensions.dll?

**Comment by blankensteiner** [comment]
Oh... seems like I can just:

```
public override IEnumerable<string> GetAssembliesForScanning()
{
    yield return "System.Threading.Tasks.Extensions";
 }
```

Could that be a solution? If yes, then I can make a new PR and we can release a 3.3.1.

**Comment by SimonCropp** [comment]
yep that should fix it. i am not at a computer, but if u pr i can merge and deploy
