### ISSUE TITLE
Class with private field is ignored for weaving

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [Fody/ConfigureAwait#11]
I have a class with ConfigureAwait(false) attribute and  private field. Fody ignores the class, doesn't add the ConfigureAwait calls and doesn't remove the attibute. If I comment out the private field, class processed by Fody as expected(verified by dotPeek).

```
 [ConfigureAwait(false)]
    public class ClassWithAttribute
    {
        private string adminPortalApiResourceId = ConfigurationManager.AppSettings["AdminPortalApi:ResourceId"];

        public async Task AsyncMethod(SynchronizationContext context)
        {
            SynchronizationContext.SetSynchronizationContext(context);
            await Task.Delay(10);
        }
}
```

[ClassWithAdttributeAndPrivateVariable.cs.txt](https://github.com/distantcam/ConfigureAwait/files/752666/ClassWithAdttributeAndPrivateVariable.cs.txt)

**Comment by vinaychandra** [comment]
@michael-freidgeim-webjet  @distantcam 
Is there an update on this issue or any workaround?

**Comment by SimonCropp** [comment]
@michael-freidgeim-webjet @vinaychandra happy to accept a PR that fixes this

**Comment by SimonCropp** [comment]
or upload a repro. will re-open if a pr or a repro is supplied
