### ISSUE TITLE
Nuget installation doesn't install Mono.Cecil.

### ISSUE THREAD

**Issue by MNF** [Fody/ConfigureAwait#12]
I've run Install-Package ConfigureAwait.Fody, but on compile time it was an error

> Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0'.

Then I Install-Package Fody, that suggested to overwrite 'FodyWeavers.xml'.
I incorrectly choose to overwrite and during compile got

> MSBUILD : error : Fody: No configured weavers. It is possible you have not installed a weaver or have installed a fody weaver nuget into a project type that does not support install.ps1. You may need to add that weaver to FodyWeavers.xml manually. eg. <Weavers><WeaverName/></Weavers>. see https://github.com/Fody/Fody/wiki/SampleUsage

It will be good if NuGet package install correct  Mono.Cecil version initially.
Also can install  merge entries in FodyWeavers.xml instead of only Skip/Overwrite?

Details of Install-Package log and compile errors attached 
[InstallPackage.txt](https://github.com/distantcam/ConfigureAwait/files/752931/InstallPackage.txt)

**Comment by SimonCropp** [comment]
if this is still an issue can u upload a repro and i will reopen

**Comment by teroneko** [comment]
When I intalled only the module ModuleInit.Fody, I got such an error. But for me I got it only when I built it with msbuild. Over Visual Studio it worked fine. Then I've thought I can install Fody, because I had often errors, when Fody was not installed, and surprise it works.

**Comment by SimonCropp** [comment]
@teroneko as the comment says. please share a repro
