### ISSUE TITLE
Code structure/readability

### ISSUE THREAD

**Issue by Anapher** [Fody/ConfigureAwait#17]
Hey,
thanks for continuing this project 👍.
While you were away, I started a fork of this project ([can be found here](https://github.com/Anapher/GlobalConfigureAwait), it's not displayed as a fork on GitHub because I actually started from scratch, tried to understand your code and merged it into my programming style and structure). My library is serving me well in my projects, but I'd also go back to your library. One thing I already noticed when I read your code is that it's not really easy to do so - you have huge files (now you have a single file that contains most of the logic) and very long variable names that make everything very complicated. I know that IL modification is always a little bit hacky and complicated, but I found it very useful to move all this IL stuff to an external file and [use a class](https://github.com/Anapher/GlobalConfigureAwait/blob/master/src/GlobalConfigureAwait/Settings/TypeLevelSettings.cs) that determines if the ConfigureAwait() should be applied for that method.

IMO the code can be made a little bit easier to read which would also motivate more people to submit pull requests. What do you think about that?

**Comment by SimonCropp** [comment]
yep that is reasonable feedback. feel free to do some restructures in a PR and we can discuss them

**Comment by Anapher** [comment]
Will do so. I have one question: Do unit tests pass on your PC? I thought I made a mistake when restructuring the project because all unit tests failed, but then I tried to run the unit tests on the upstream they also fail, all with the same error:
```
System.TypeInitializationException : Der Typeninitialisierer für "ModuleWeaverTests" hat eine Ausnahme verursacht.
---- System.Exception : The files have difference peverify results.

AfterOutput:
Alle Klassen und Methoden in C:\Users\anaph\Downloads\ConfigureAwait-master\ConfigureAwait-master\Tests\bin\Debug\net46\fodytemp\AssemblyToProcess.dll bestätigt.


BeforeOutput:
Alle Klassen und Methoden in C:\Users\anaph\Downloads\ConfigureAwait-master\ConfigureAwait-master\Tests\bin\Debug\net46\AssemblyToProcess.dll bestätigt.

   bei ModuleWeaverTests..ctor()
----- Inner Stack Trace -----
   bei Fody.PeVerifier.ThrowIfDifferent(String beforeAssemblyPath, String afterAssemblyPath, IEnumerable`1 ignoreCodes, String workingDirectory)
   bei Fody.WeaverTestHelper.ExecuteTestRun(BaseModuleWeaver weaver, String assemblyPath, Boolean runPeVerify, Action`1 afterExecuteCallback, Action`1 beforeExecuteCallback, String assemblyName, IEnumerable`1 ignoreCodes)
   bei ModuleWeaverTests..cctor()
```

**Comment by SimonCropp** [comment]
@Anapher sorry for the delayed response. can u try again?
