### ISSUE TITLE
Update to Fody 3.0

### ISSUE THREAD

**Issue by SimonCropp** [Fody/ConfigureAwait#18]

**Comment by HarshDaga** [comment]
`MSBUILD : error : Fody: The weaver assembly 'ConfigureAwait.Fody, Version=2.1.4.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll. Expected strong name token of '50-CE-BF-1C-CE-B9-D0-5E' but got '1C-A0-91-87-7D-12-CA-03'. The weaver needs to update to at least version 3.0 of FodyHelpers.`

**Comment by SimonCropp** [comment]
@HarshDaga please raise a new issue, and also ensure you read the issue template

**Comment by HarshDaga** [comment]
It's not really an issue tbh, it's just that the nuget package is outdated.
Can you create a new release for the latest commit?

**Comment by SimonCropp** [comment]
@HarshDaga i think it a little more complicated than that. this works https://github.com/Fody/FodyAddinSamples/blob/master/ConfigureAwaitSample/ConfigureAwaitSample.csproj

and the current nuget already references v3 of fody

![image](https://user-images.githubusercontent.com/122666/50535223-0d73b000-0b9c-11e9-9329-ffb377da5b84.png)
