### ISSUE TITLE
Assembly-level ConfigureAwaitAttribute does not work with .NetStandard 2.0 Assembly

### ISSUE THREAD

**Issue by borbmizzet** [Fody/ConfigureAwait#19]
I can't get this working globally with a .netstandard2.0 assembly.
You can't add it as an AssemblyAttribute in an ItemGroup in the .csproj because the parameter can only be a string for that, not a bool. (see [https://docs.microsoft.com/en-us/visualstudio/msbuild/writecodefragment-task](https://docs.microsoft.com/en-us/visualstudio/msbuild/writecodefragment-task)

and if I set
`<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`
and set 
`[assembly: Fody.ConfigureAwait(false)]` in an AssemblyInfo.cs file it just gets ignored, unlike all the other AssemblyAttributes in that file.  According to JetBrains dotPeek, the Custom Attribute Fody.ConfigureAwait isnt even included in the assembly, and none of the awaited calls are set to configureawait(false).  I checked the generated assemblies in both the bin and obj folders.

**Comment by borbmizzet** [comment]
[ConfigureAwait.Fody.Test.zip](https://github.com/Fody/ConfigureAwait/files/1916565/ConfigureAwait.Fody.Test.zip)

**Comment by SimonCropp** [comment]
sorry. no idea when i will get to this. a PR that fixes the issue would help

**Comment by SimonCropp** [comment]
use ILSpy instead of dotPeek. dotpeek will lie to you but looking at the pdb to find the source and should the the original source file.

if u look in ilspy you will see the correct code is being injected

![image](https://user-images.githubusercontent.com/122666/41873608-d8f0e314-7908-11e8-96bc-2c0e6803ec20.png)
