### ISSUE TITLE
ConfigureAwait 2.1.2 - bad assembly used for compiling

### ISSUE THREAD

**Issue by Nekromancer** [Fody/ConfigureAwait#25]
It happens on 2.1.2 version (2.1.1 works just fine).

I have CsProj2017 (new project format) targeting net47 framework. While compiling i get an error like this:

```
Fody: An invalid weaver file has been passed in: ~\.nuget\packages\configureawait.fody\2.1.2\build\..\netstandardweaver\ConfigureAwait.Fody.dll
```

It seems like Fody is trying to run netstandard weaver on net47 library. Minimal reproduction project:
[repro.zip](https://github.com/Fody/ConfigureAwait/files/2436859/repro.zip)

**Comment by SimonCropp** [comment]
fixed, pending a nuget cache update
