### ISSUE TITLE
Missing releases and tags

### ISSUE THREAD

**Issue by ramonsmits** [Fody/ConfigureAwait#33]
I've noticed that the last mentioned release in the repo is 2.1.0 while several new releases have been made.

**Comment by SimonCropp** [comment]
@ramonsmits i tend not to go to the effort to create releases. it seems redundant when there are already milestones to see what has changed. https://github.com/Fody/ConfigureAwait/milestones?state=closed  yes some were missing so i have added the missing milestones and tags

**Comment by SimonCropp** [comment]
also https://github.com/Fody/ConfigureAwait/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#you-should-already-be-a-patron

> To be using Fody you should be a Patron. See Licensing/Patron FAQ. With that in mind, it is assumed anyone raising an issue is already a Patron. As such your GitHub Id may be verified against the OpenCollective contributors. This process will depend on the issue quality, your circumstances, and the impact on the larger user base.
