### ISSUE TITLE
Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by Dunge** [Fody/ConfigureAwait#353]
Visual Studio 2019
Net5.0
Fody 6.5.2
ConfigureAwait.Fody 3.3.1

#### Describe the issue

        public async Task Start()
        {
            if (_someObject != null)
                await _someObject?.SomeAsyncFunc();
        }

The weaver seems to generate invalid IL code when having a null check AND a null propagation operator.

It throws "Common Language Runtime detected an invalid program" when executing the method.

Opening the resulting .dll file using dotPeek and selecting "Decompiled Sources" write "// ISSUE: unable to decompile the method." inside the method.

Removing either the "if" check or the "?." operator fix it.

#### Minimal Repro

https://gist.github.com/Dunge/190433d57a370adfb35085920451e11f

**Comment by SimonCropp** [comment]
@Dunge how are you going with producing a fix?

**Comment by Dunge** [comment]
@SimonCropp Hmm? With all due respect, if I had any idea I would have produced a PR, not an Issue.

Fody's code is way out of my field of expertise. As a nuget consumer, the reason we use weavers is to simplify our codebase, not to enter the world of expert IL stack analysis. The goal is to report it so that it at least get acknowledged as an issue and documented, and hopefully then to get picked up by project managers who can then use their knowledge to solidify their product.

It took me a few days just to trim down my project trying to find out what caused my service misbehavior, to limit to scope to a single method, and finally to realize Fody is causing the issue. Then it took me a few additional hours to create the "Minimal Repro" in order to share it here because just a few different line or characters can cause the behavior to change.

For your information, this was used in a generic host Windows Service environment, and triggered during the "Stop" procedure. This caused the process to become stuck in "Suspended" state in the Task Manager and would remain there, impossible to task kill even with full permissions, something I never encountered in Windows before. It required a full OS reboot to get rid of, which caused mass headaches for our production servers.

On a separate note, I believe I also encountered the same problem as #244 when combining ConfigureAwait.Fody with  StephenCleary's AsyncEx library and using AsyncLock. [You can read more about it here](https://github.com/StephenCleary/AsyncEx/issues/230). Unfortunately I was unable to create a minimal repro, so I didn't share it here. It just goes to show that there are a few situation where using ConfigureAwait.Fody breaks the software.

Without wanting to be rude, the best I can offer is modifying readme.md and add a warning that this weaver have know dangerous issues and not to use in production environments.

**Comment by SimonCropp** [comment]
i will take a look at it

just to confirm. are all your devs that are using fody patrons on open collective? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by SimonCropp** [comment]
closed due to no response

**Comment by SimonCropp** [comment]
@Dunge still happy to accept a PR if you change your mind and want to contribute
