### ISSUE TITLE
Didn't work at Net6

### ISSUE THREAD

**Issue by LukyanovOleg** [Fody/ConfigureAwait#391]
I followed the instructions in the project at NET6 but i didn't get transform code in compiled viersion. What i did wrong.

config:
```xml
    <PackageReference Include="Fody">
      <Version>6.5.1</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ConfigureAwait.Fody">
      <Version>3.3.1</Version>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```
    
FodyWeavers.xml:
```xml
<Weavers>
  <ConfigureAwait ContinueOnCapturedContext="false"/>
</Weavers>
```
Code:

    [ConfigureAwait(false)]
    class TestClass
    {
        public async Task MyMethodAsync()
        {
            await Task.Delay(10);
            await Task.Delay(20);
            
        }
   }

**Comment by SimonCropp** [comment]
please raise a new issue and read the issue template

**Comment by brutaldev** [comment]
Here is a new issue regarding this: https://github.com/Fody/ConfigureAwait/issues/430
