### ISSUE TITLE
ConfiguredTaskAwaitable`1' was used with the wrong number of generic arguments 

### ISSUE THREAD

**Issue by JMnITup** [Fody/ConfigureAwait#4]
I love the ConfigureAwait class decorator, and it has worked very well for me until now.  I haven't quite figured out why this is occurring, but I now have a class that compiles fine, but when called (specifically from another assembly, in this case the unit test assembly covering the code, not sure if it would fail locally yet), it throws the following exception:

`{"The generic type 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable``1' was used with the wrong number of generic arguments in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.":"System.Runtime.CompilerServices.ConfiguredTaskAwaitable``1"}`
(Sorry, can't figure out how to escape the code apostrophe, so doubled it, which makes a weird space instead of that apostrophe :/  )

When compiled, everything compiles and Fody seems to run ConfigureAwait properly
(I replaced actual assembly name and project directory with {AssemblyName} and {ProjectDirectory} tokens):
8>    Fody: Fody (version 1.29.3.0) Executing
8>      Fody/ConfigureAwait:    Removing reference to 'ConfigureAwait.dll'.
8>    Fody:   Finished Fody 152ms.
8>  {AssemblyName} -> C:\Users{ProjectDirectory}\bin\Debug{AssemblyName}.dll
8>    Fody:   Skipped Verifying assembly since it is disabled in configuration
8>    Fody:   Finished verification in 0ms.
========== Rebuild All: 8 succeeded, 0 failed, 0 skipped ==========

This is using the latest version of Fody and Fody.ConfigureAwait from NuGet (1.29.3.0 and 0.2.0 respectively).  

The exception is thrown on the call into the assembly through a public interface method, and never gets into the class itself... it is a call against an async method, with an await on the call, but as a point of reference it does the same thing whether awaited or not (which makes sense, because it is never getting to the point of any return task in the first place)

This goes away completely by simply removing the ConfigureAwait decoration on the class.  Presence or absence of actual configureawait calls on the awaits inside of that class make no difference in any case (which again makes sense, but I thought MAYBE something with the way it was tweaking the bytecode was somehow causing an issue).  The Fody and configureawait reference in the project and class do not cause issues, only when taken to actually decorating the class.  This occurs when compiled both x64 and x86

For now I've just taken off the decoration and manually added .ConfigureAwait to all awaits (painful :(  ), but would love to figure out what is causing this so I can fix.

Thanks!

**Comment by distantcam** [comment]
Please try 0.3.0
