### ISSUE TITLE
High memory usage of ConfigureAwait.Fody

### ISSUE THREAD

**Issue by kmsitinfra** [Fody/ConfigureAwait#493]
#### Preamble

What is in use:

Fody 6.6.0
ConfigureAwait.Fody 3.3.1 (configured as MSBuild property in project file)
.NET SDK 5.0.301, MSBuild 16.10
Windows Server 2019. 64bit, 16GB RAM, 8vCPU à 2.3GHz (Hyper-V VM)

#### Describe the issue

During our build with Fody we are experiencing a high RAM usage of about 4-8GB per msbuild.exe. If we disable ConfigureAwait.Fody we see an average usage about ~1GB per msbuild.exe. Because of that, with our build machine (16GB Memory) we are experiencing out of memory exceptions.

#### Minimal Repro

If we provide a minimal repo, the ram usage isn't high with an nearly empty repository and we are not allowed to share our code.

#### Make an effort to fix the bug

We have been testing this with diffrent machines. If we use a 32GB RAM Machine, the build is working. We would like to now, why the RAM usage is so much higher with activated ConfigureAwait.Fody. 

Happy for any hints or ideas, thank you.

**Comment by SimonCropp** [comment]
@kmsitinfra how much ram is used if you round trip the assembly using Cecil?

**Comment by kmsitinfra** [comment]
We wrote a simple Mono.Cecil consoleApp (see sample attached) which inserts to all methods of all assemblies an "Debugger.Break();" This only uses 50 – 100MB of RAM.
Was this your intention of test?

Happy for any hints or ideas, thank you.
[sample.txt](https://github.com/Fody/ConfigureAwait/files/9665461/sample.txt)

**Comment by SimonCropp** [comment]
@kmsitinfra

> Was this your intention of test?

to see if the problem is due to cecil or configureawait

**Comment by marcoerni** [comment]
@SimonCropp

According to the round trip test with Cecil, we do not expect the issue in Cecil.
Do you have any ideas what lead to the high memory usage? Can we provide any further information or do some more tests?

Currently ConfigureAwait is the only plugin we use with Fody. Should we test with another one to see if the problem is due fody itself?

**Comment by SimonCropp** [comment]
without a way to reproduce it i dont know if there is a way forward
