### ISSUE TITLE
When using multiple target frameworks, only one of the assemblies gets weaved

### ISSUE THREAD

**Issue by Tyrrrz** [Fody/ConfigureAwait#56]
**Setup:**

`*.csproj`:
```xml
<TargetFrameworks>net45;netstandard2.0</TargetFrameworks>
```

and

```xml
<ItemGroup>
  <PackageReference Include="ConfigureAwait.Fody" Version="3.1.0" PrivateAssets="all" />
</ItemGroup>
```

`FodyWeavers.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd">
  <ConfigureAwait ContinueOnCapturedContext="false" />
</Weavers>
```

**Expected result:** both libraries get weaved with `.ConfigureAwait(false)`.

**Actual result:** only the .NET Standard 2.0 version of the assembly gets weaved, the other (.net45) one is untouched and lacks `ProcessedByFody` class injected. (Checked with dnSpy)

I'm not sure if this is `ConfigureAwait.Fody` specific or not, but at least `NotifyPropertyChanged.Fody` seems to work in a situation similar to this one.

Here's a link to a build that reproduces this: https://ci.appveyor.com/project/Tyrrrz/cliwrap/builds/23491619

Here's a link to the *.csproj at this commit: https://github.com/Tyrrrz/CliWrap/blob/ddab02503b03577f3e9e0635f3b6724523de59f7/CliWrap/CliWrap.csproj

**Comment by SimonCropp** [comment]
Did u use ilspy to confirm the result?

**Comment by Tyrrrz** [comment]
Yes, both dnSpy and ILSpy show the same result.

**Comment by SimonCropp** [comment]
Ok can u read the issue template and do the missing parts https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Tyrrrz** [comment]
Ok I narrowed down and it looks like it simply doesn't work on net45, while net452 and up seem fine.

>Ok can u read the issue template and do the missing parts 

Which ones?

**Comment by SimonCropp** [comment]
it seems only net452 and above are supported https://github.com/Fody/ConfigureAwait/blob/master/ConfigureAwait/ConfigureAwait.csproj#L4

> Which ones?

 * [You should already be a Patron](https://github.com/Fody/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md#you-should-already-be-a-patron)
 * ensure you are using the current stable versions of Fody (note for this you need an explicit NuGet reference to Fody in your csproj)
