### ISSUE TITLE
PEVerify failure

### ISSUE THREAD

**Issue by IanYates** [Fody/ConfigureAwait#8]
Hi,

Great library.  I make use of the AsyncEx library from @StephenCleary (https://github.com/StephenCleary/AsyncEx).

A big part of that is the AsyncLock class where the pattern of use is

```C#
using(await locker.LockAsync()) 
{
  //do my stuff

}
```

Because Task implements IDisposable, if LockAsync simply returned Task then it's easy to accidentally do

```C#
using (locker.LockAsync())
{


}
```

This still compiles and runs but quickly breaks at runtime after your first pass through as the lock is never released through disposal - rather the task used to wait to acquire the lock is disposed instead.

He came up with a novel approach of wrapping the returned Task in a struct that is still awaitable but is not disposable.  It has implicit conversions to Task.  See https://github.com/StephenCleary/AsyncEx/blob/master/Source/Nito.AsyncEx%20(NET45,%20Win8,%20WP8,%20WPA81)/AwaitableDisposable.cs
The nice thing is that the bad code above does not compile.

I have quite a few classes in my code where I needed a similar pattern of an async resource acquisition and then relied on IDisposable for cleanup (many times this involves a trip through that AsyncLock too!).  Unfortunately I think this library does not like the use of this pattern.  My code mostly runs but I get nasty errors in certain methods.  I've been mucking with my code and occasionally got `JIT Compiler encountered an internal limitation` but usually get `Common language runtime detected an invalid program`.
Using a tool like JustDecompile to inspect the modified code throws errors when examining the failing method.
Enabling PEVerify in the Fody configuration also flags errors.  
Examples
```
2>MSBUILD : error : [IL]: Error: [C:\dev\dox.net\Dox.Server.Web\bin\Dox.Server.Web.dll : Dox.Server.Web.UserSession.WebSessionManager+<AddPendingSession>d__10::MoveNext][offset 0x0000008B][found value 'System.Runtime.CompilerServices.TaskAwaiter`1[Dox.Server.Web.Repositories.ISharedLockToken]'][expected value 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Dox.Server.Web.Repositories.ISharedLockToken]'] Unexpected type on the stack.(Error: 0x80131854)
2>MSBUILD : error : [IL]: Error: [C:\dev\dox.net\Dox.Server.Web\bin\Dox.Server.Web.dll : Dox.Server.Web.UserSession.WebSessionManager+<AddSession>d__11::MoveNext][offset 0x000000A1][found value 'System.Runtime.CompilerServices.TaskAwaiter`1[Dox.Server.Web.Repositories.ISharedLockToken]'][expected value 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Dox.Server.Web.Repositories.ISharedLockToken]'] Unexpected type on the stack.(Error: 0x80131854)
2>MSBUILD : error : [IL]: Error: [C:\dev\dox.net\Dox.Server.Web\bin\Dox.Server.Web.dll : Dox.Server.Web.PAS.LegacyPas+<>c__DisplayClass8_0+<<SyncPatients>b__3>d::MoveNext][offset 0x00000112][found value 'System.Runtime.CompilerServices.TaskAwaiter`1[Dox.Server.Web.PAS.LegacyPas+ProcAndDb]'][expected value 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Dox.Server.Web.PAS.LegacyPas+ProcAndDb]'] Unexpected type on the stack.(Error: 0x80131854)
2>MSBUILD : error : [IL]: Error: [C:\dev\dox.net\Dox.Server.Web\bin\Dox.Server.Web.dll : Dox.Server.Web.PAS.LegacyPas+<>c__DisplayClass9_0+<<SyncPatientsByDate>b__0>d::MoveNext][offset 0x00000140][found value 'System.Runtime.CompilerServices.TaskAwaiter`1[Dox.Server.Web.PAS.LegacyPas+ProcAndDb]'][expected value 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[Dox.Server.Web.PAS.LegacyPas+ProcAndDb]'] Unexpected type on the stack.(Error: 0x80131854)
2>MSBUILD : error : [IL]: Error: [C:\dev\dox.net\Dox.Server.Web\bin\Dox.Server.Web.dll : Dox.Server.Web.Notification.DicomNotificationProvider+<OnFormInstanceRecordChanged>d__13::MoveNext][offset 0x0000003C][found value 'System.Runtime.CompilerServices.TaskAwaiter`1[System.IDisposable]'][expected value 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[System.IDisposable]'] Unexpected type on the stack.(Error: 0x80131854)
```

That `unexpected type on the stack` error is what makes me think this library is slotting in `Task` when the compiler is expecting that struct instead.  Am I on the right track with my thinking?  Do you think this is a smallish problem to solve?  I haven't browsed through this repository yet to get a handle on how hard such a change, assuming it's likely to succeed, is to make but am happy to contribute a PR (will take a while) or at least get some more concrete debugging output for you.

Thanks!

**Comment by SimonCropp** [comment]
can u upload a repro?

**Comment by SimonCropp** [comment]
well re-open when a repro is supplied
